name: pdoc
on:
  push:
    branches: [ main ]
jobs:
  pdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install . pdoc; python -m pdoc -o html kinematics
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html
